version: 2

sources:
  - name: staging
    database: capstone-proj-464212
    schema: stg_data
    tables:
      - name: stg_us_blue_chips

models:
  - name: stg_us_blue_chips_stocks
    description: >
      Stocks data from US Blue Chips Stocks.
