version: 2

models:
  - name: fact_us_blue_chips
    description: >
      Table contains US Blue Chips data prices and volume with averages and volatility.
    columns:
      - name: open_price
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000
              strictly: true
      - name: lowest_price
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000
              strictly: true
      - name: highest_price
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000
              strictly: true
      - name: closing_price
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000
              strictly: true

  - name: dim_companies
    description: >
      Dimension table containing blue chips stocks company name and ticker

  - name: monthly_analysis.sql
    description: >
      Contains monthly average for recent stock prices 2020-present

  - name: yearly_analysis.sql
    description: >
      Contains yearly average for recent stock prices 2020-present
  
  - name: merged_yearly_monthly_gains.sql
    description: >
      Contains yearly and monthly average for recent stock prices 2020-present
  
  - name: above_moving_averages
    description: >
      Shows if stock is above its moving average or volatility for the day